language: android
dist: trusty
android:
  components:
    - platform-tools
    - tools

script:
    - yes | sdkmanager "platforms;android-29"
    - yes | sdkmanager "build-tools;29.0.0"
    - ./gradlew test jacocoTestReport coveralls
